[package]
name = "quic-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
hkdf = "0.12.4"
aes = "0.8.4"
sha2 = "0.10.8"
hex-literal = "0.4.1"
aes-gcm = "0.10.3"
hex = "0.4.3"
