[package]
name = "quic-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
hex = "0.4.3"
s2n-quic-core = "0.45.0"
s2n-quic-crypto = "0.45.0"
hkdf = "0.12.4"
ecb = "0.1.2"
aes = "0.8.4"
sha2 = "0.10.8"
hex-literal = "0.4.1"
ring = "0.17.8"
